# Generated by Django 6.0.5 on 2026-05-09 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='source_post_id',
            field=models.CharField(blank=True, default='', max_length=64, unique=True, verbose_name='原帖 ID'),
        ),
    ]
