# Generated by Django 6.0.5 on 2026-05-22 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_invite_code_days_and_fk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mch_order_no', models.CharField(max_length=64, unique=True, verbose_name='商户订单号')),
                ('sys_order_no', models.CharField(blank=True, max_length=64, verbose_name='系统订单号')),
                ('plan', models.CharField(choices=[('daily', '日卡 8.8 元 / 1 天'), ('monthly', '月卡 88 元 / 30 天')], max_length=16, verbose_name='套餐')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='金额（元）')),
                ('days', models.PositiveIntegerField(verbose_name='授权天数')),
                ('status', models.CharField(choices=[('pending', '待支付'), ('paid', '已支付'), ('failed', '支付失败'), ('expired', '已过期')], default='pending', max_length=16, verbose_name='订单状态')),
                ('pay_url', models.URLField(blank=True, verbose_name='支付链接')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('notify_payload', models.JSONField(blank=True, null=True, verbose_name='回调原文')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pay_orders', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '支付订单',
                'verbose_name_plural': '支付订单',
                'ordering': ['-created_at'],
            },
        ),
    ]
