# Generated by Django 6.0.5 on 2026-05-23 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_payorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerifyCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='邮箱')),
                ('code', models.CharField(max_length=8, verbose_name='验证码')),
                ('purpose', models.CharField(choices=[('register', '注册')], default='register', max_length=16, verbose_name='用途')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='生成时间')),
                ('consumed_at', models.DateTimeField(blank=True, null=True, verbose_name='消费时间')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='请求IP')),
            ],
            options={
                'verbose_name': '邮箱验证码',
                'verbose_name_plural': '邮箱验证码',
                'ordering': ['-created_at'],
            },
        ),
    ]
